---
- hosts: all

  tasks:

    # Install the Ruby and Gemspec pieces
    - name: Latest version of Ruby is installed
      become: true
      apt: pkg={{ item }} state=latest
      with_items:
        - "ruby2.0"
        - "ruby2.0-dev"

    - name: Symlink exists for Ruby and Gemsspec
      become: true
      file: src=/usr/bin/{{ item }}2.0 dest=/usr/local/bin/{{ item }} state=link
      with_items:
        - "gem"
        - "ruby"

    # Install the NodeJS pieces
    - name: Install the gpg key for nodejs LTS
      become: true
      apt_key:
        url: "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
        validate_certs: no

    - name: Install the nodejs LTS repos
      become: true
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install NodeJs
      become: true
      apt:
        name: nodejs
        state: present

    - name: Install PM2
      become: true
      command: npm install -g pm2

    - name: Create PM2 service
      become: true
      command: env PATH=$PATH:/usr/bin pm2 startup upstart -u ubuntu --hp /home/ubuntu

    - name: PM2 startup configuration (pm2 start)
      command: pm2 start bin/www --name="nodejs-app"
      args:
        chdir: /home/ubuntu/nodejs-app/

    - name: PM2 startup configuration (pm2 save)
      command: pm2 save
