---
- hosts: all

  pre_tasks:
    - name: Update legacy Python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:

     - apt_repository:
       repo: ppa:brightbox/ruby-ng

    # Install the Ruby and Gemspec pieces
    - name: Latest version of Ruby is installed
      become: true
      apt:
        name: {{ item }}
        state: present
        update_cache: true
      with_items:
        - "ruby2.3"
        - "ruby2.3-dev"


    - name: Install SafeYAML gem with proper $PATH
      gem:
        name: safe_yaml
        user_install: no

    # Install the NodeJS pieces
    - name: Install the gpg key for nodejs LTS
      become: true
      apt_key:
        url: "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
        validate_certs: no

    - name: Install the nodejs LTS repos
      become: true
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install NodeJs
      become: true
      apt:
        name: nodejs
        state: present

    - name: Install PM2
      become: true
      command: npm install -g pm2

    - name: Create PM2 service
      become: true
      command: env PATH=$PATH:/usr/bin pm2 startup upstart -u ubuntu --hp /home/ubuntu


    # If this is a local build lets do it a bit diff for testing...
    - name: "Install GIT"
      become: true
      apt:
        name: git
      state: present
      when:
        - is_local == "true"

    - name: "Clone our source repository"
      become: true
      become_user: ubuntu
      command: git clone https://github.com/ehime/nodejs-app.git /home/ubuntu/nodejs-app
      when:
        - is_local == "true"

    - name: "Move testing scripts"
      become: true
      become_user: ubuntu
      command: mv /home/ubuntu/nodejs-app/packer/serverspec_tests /tmp/tests
      when:
        - is_local == "true"



    # End our case...


    - name: PM2 startup configuration (pm2 start)
      command: /usr/bin/pm2 start bin/www --name="nodejs-app"
      args:
        chdir: /home/ubuntu/nodejs-app/

    - name: PM2 startup configuration (pm2 save)
      command: /usr/bin/pm2 save
